# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ksk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(unique=True, verbose_name='Numer karty: ')),
                ('name', models.CharField(max_length=50, verbose_name='Imię: ')),
                ('surname', models.CharField(max_length=100, verbose_name='Nazwisko: ')),
                ('street', models.CharField(max_length=255, verbose_name='Ulica: ')),
                ('apartement_number', models.CharField(max_length=5, verbose_name='Nr. mieszkania')),
                ('building_number', models.CharField(max_length=5, verbose_name='Nr. budynku: ')),
                ('city', models.CharField(max_length=255, verbose_name='Miejscowość: ')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Kod pocztowy: ')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(null=True, verbose_name='Nr. telefonu: ')),
                ('purchase_value', models.FloatField(null=True, verbose_name='Wartość zakupów: ')),
                ('discount', models.IntegerField(null=True, verbose_name='Rabat: ')),
            ],
            options={
                'verbose_name': 'Karta stałego klienta',
                'verbose_name_plural': 'Karta stałego klienta',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=100, verbose_name='Nazwa artykułu: ')),
                ('plu_num', models.IntegerField(default=0, unique=True, verbose_name='Nr. PLU')),
                ('sales_price_brutto', models.FloatField(null=True, verbose_name='CSB: ')),
                ('sales_price_netto', models.FloatField(null=True, verbose_name='CSN: ')),
                ('last_price', models.FloatField(null=True, verbose_name='Ostatnia cena sprzedaży: ')),
                ('purchase_price_brutto', models.FloatField(null=True, verbose_name='CZB: ')),
                ('purchase_price_netto', models.FloatField(null=True, verbose_name='CZN: ')),
                ('vat_difference', models.FloatField(null=True, verbose_name='Różnica VAT: ')),
                ('vat_value', models.CharField(choices=[('23', 23), ('8', 8), ('5', 5), ('0', 0)], default=23, max_length=3)),
                ('entry_date', models.DateField(verbose_name='Data wejścia: ')),
                ('margin', models.FloatField(null=True, verbose_name='Marża: ')),
                ('zloty_margin', models.FloatField(null=True, verbose_name='Marża złotówkowa: ')),
                ('stock', models.IntegerField(default=0, verbose_name='Stan: ')),
                ('stock_cs_pln', models.FloatField(null=True, verbose_name='Stok CS PLN: ')),
                ('stock_cz_pln', models.FloatField(null=True, verbose_name='Stok CZ PLN: ')),
                ('decote', models.IntegerField(default=0, verbose_name='Dekot: ')),
                ('price_raw_variance', models.FloatField(null=True)),
                ('price_percentage_variance', models.FloatField(default=0.0)),
                ('price_changes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_name', models.CharField(max_length=255, verbose_name='Nazwa stoiska: ')),
                ('adress', models.CharField(max_length=255, verbose_name='Adres: ')),
            ],
            options={
                'verbose_name': 'Stoisko',
                'verbose_name_plural': 'Stoiska',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu_list', models.CharField(max_length=255)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('is_ksk', models.BooleanField(default=False)),
                ('ksk_num', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='panel.Product'),
        ),
    ]
