# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_historicalproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
    ]
