# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0003_auto_20171227_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('art_name', models.CharField(max_length=100, verbose_name='Nazwa artykułu: ')),
                ('plu_num', models.IntegerField(db_index=True, default=0, verbose_name='Nr. PLU')),
                ('sales_price_brutto', models.FloatField(null=True, verbose_name='CSB: ')),
                ('sales_price_netto', models.FloatField(null=True, verbose_name='CSN: ')),
                ('last_price', models.FloatField(null=True, verbose_name='Ostatnia cena sprzedaży: ')),
                ('purchase_price_brutto', models.FloatField(null=True, verbose_name='CZB: ')),
                ('purchase_price_netto', models.FloatField(null=True, verbose_name='CZN: ')),
                ('vat_difference', models.FloatField(null=True, verbose_name='Różnica VAT: ')),
                ('vat_value', models.CharField(choices=[('23', 23), ('8', 8), ('5', 5), ('0', 0)], default=23, max_length=3)),
                ('entry_date', models.DateField(verbose_name='Data wejścia: ')),
                ('margin', models.FloatField(null=True, verbose_name='Marża: ')),
                ('zloty_margin', models.FloatField(null=True, verbose_name='Marża złotówkowa: ')),
                ('stock', models.IntegerField(default=0, verbose_name='Stan: ')),
                ('stock_cs_pln', models.FloatField(null=True, verbose_name='Stok CS PLN: ')),
                ('stock_cz_pln', models.FloatField(null=True, verbose_name='Stok CZ PLN: ')),
                ('decote', models.IntegerField(default=0, verbose_name='Dekot: ')),
                ('price_raw_variance', models.FloatField(null=True)),
                ('price_percentage_variance', models.FloatField(default=0.0)),
                ('price_changes', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Produkt',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
