# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_historicalproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='zloty_margin',
            field=models.FloatField(null=True, verbose_name='Marża PLN: '),
        ),
        migrations.AlterField(
            model_name='product',
            name='zloty_margin',
            field=models.FloatField(null=True, verbose_name='Marża PLN: '),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
