# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20180106_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksk',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Liczba punktów'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
