# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20180116_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
