# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_stand_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='user',
        ),
    ]
