# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_productinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='user',
        ),
    ]
