# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('panel', '0016_productinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductInfo',
        ),
    ]
