# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_auto_20180117_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='plu_num',
            field=models.IntegerField(default=0, verbose_name='Nr. PLU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='plu_num',
            field=models.IntegerField(default=0, verbose_name='Nr. PLU'),
        ),
    ]
