# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_auto_20180117_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
