# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_transaction_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksk',
            name='purchase_value',
            field=models.FloatField(default=0.0, verbose_name='Wartość zakupów: '),
        ),
    ]
