# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_auto_20180119_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='quantity_sold',
            field=models.IntegerField(default=0, verbose_name='Sprzedana ilość'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.IntegerField(default=0, verbose_name='Sprzedana ilość'),
        ),
    ]
