# Generated by Django 2.0.2 on 2018-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_auto_20180524_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_status',
            field=models.CharField(choices=[('AC', 'AC'), ('NC', 'NC')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('AC', 'AC'), ('NC', 'NC')], default='AC', max_length=2),
        ),
    ]
