# Generated by Django 2.0.2 on 2018-11-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0025_auto_20180524_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
