# Generated by Django 2.0.2 on 2018-11-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_auto_20181110_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu_num', models.IntegerField(null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
