# Generated by Django 2.0.2 on 2018-11-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_price',
            field=models.FloatField(null=True),
        ),
    ]
